// Adapter: public web/auction search "discovery" for an exact VIN.
//
// IMPORTANT: This adapter does NOT scrape search engines or auction sites (that would
// risk violating robots.txt/ToS and could require bypassing access controls). Instead it
// deterministically builds a set of public, indexable search URLs for the exact VIN string
// so a human reviewer can open them and manually capture any evidence found. Nothing here
// is fabricated as evidence - each entry is explicitly UNKNOWN until a human records an observation.
//
// v0.1.3: leads are generated by the privacy-first search pack (Startpage/Brave/DDG first;
// Google is optional/opt-in).
import { NormalizedRecord } from "../types";
import { buildSearchPack, searchPackToLeads } from "../engine/searchPack";

export interface SearchLead {
  label: string;
  url: string;
}

export function buildVinSearchLeads(vin: string): SearchLead[] {
  return searchPackToLeads(buildSearchPack(vin));
}

export function buildSearchDiscoveryRecord(vin: string, leads: SearchLead[]): NormalizedRecord {
  return {
    vin,
    source: "Public Search Discovery",
    source_url: null,
    retrieved_at: new Date().toISOString(),
    event_date: null,
    event_type: "search_leads_generated",
    mileage: null,
    mileage_unit: null,
    location: null,
    title_status: null,
    damage: null,
    raw_excerpt: `Generated ${leads.length} privacy-first search-pack lead(s) for exact-VIN review (SEARCH_LEADS_GENERATED, not SEARCH_COMPLETED). No pages were fetched or scraped; open the pack (or browser addon) and record source observations manually.`,
    evidence_type: "UNKNOWN",
    confidence: "LOW",
    provenance: {
      kind: "GENERATED_LEAD",
      origin: "VIN Recon search pack",
      independenceKey: "generated-search-leads",
      relationship: "UNKNOWN",
      independentlyRetrieved: false,
      note: "URLs were generated; their contents were not retrieved.",
    },
  };
}
